import type { Metadata } from "next";
import { Inter, Mouse_Memoirs } from "next/font/google"; // import fontul
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const mouse = Mouse_Memoirs({
  variable: "--font-mouse",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${mouse.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
